listen-address  0.0.0.0:8118
logdir  /tmp
logfile  privoxy.log
toggle  1
enable-remote-toggle  0
enable-edit-actions  0
accept-intercepted-requests  0
buffer-limit  8192
forward-socks5t  /  127.0.0.1:1080  .
